name: calculator_app
description: "A new Flutter project with AdMob integration."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons (default iOS-style icons)
  cupertino_icons: ^1.0.8

  # ✅ Google Mobile Ads (latest)
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ✅ Latest lint rules
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Uncomment and add assets if you want to use images
  # assets:
  #   - assets/images/

  # Uncomment if you add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
